name: example
description: A flutterwave example project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutterwave_standard:
    path: "../"
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
flutter:
  uses-material-design: true
